export const API_GET_ASSET_DETAIL = "/api/asset/detail"
export const API_ASSET_DELIVERY_HISTORY_DETAIL = "/api/asset/delivery-history/detail"
export const API_ASSET_DELIVERY_HISTORY_LIST = "/api/asset/delivery-history/list"
export const API_ASSET_MAINTENANCE_LIST = "/api/asset/maintenance/list"
export const API_ASSET_MAINTENANCE_DETAIL = "/api/asset/maintenance/detail"
export const API_ASSET_DELIVERY_HISTORY_CREATE = "/api/asset/delivery-history/create"
export const API_ASSET_MAINTENANCE_CREATE = "/api/asset/maintenance/create"
export const API_ASSET_SEARCH = "/api/search"
